apiVersion: batch/v1
kind: Job
metadata:
  name: order-processing-job
  namespace: hackathon
spec:
  template:
    spec:
      containers:
      - name: order-processing
        image: curlimages/curl:latest
        command: ["curl"]
        args: ["http://order-service.hackathon.svc.cluster.local:8080/api/v1/process-orders"]
      restartPolicy: Never
  backoffLimit: 3
